# Generated by Django 3.2.8 on 2022-07-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEmergency',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_relation', models.CharField(max_length=30, verbose_name='Relación Parentesca')),
                ('contact_phone', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('contact_firstname', models.CharField(max_length=60, verbose_name='Nombres')),
                ('contact_lastname', models.CharField(max_length=30, verbose_name='Apellidos')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('perfil_id', models.AutoField(primary_key=True, serialize=False)),
                ('perfil_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_rut', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('worker_firstname', models.CharField(max_length=30, verbose_name='Nombres')),
                ('worker_lastname', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('worker_address', models.CharField(max_length=60, verbose_name='Dirección')),
                ('worker_phone', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('worker_gender', models.CharField(max_length=30, verbose_name='Género')),
                ('worker_companyDate', models.DateField()),
            ],
        ),
    ]
