# Generated by Django 3.2.8 on 2022-07-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20220723_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_gender',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')], default=1, verbose_name='Género'),
        ),
    ]
