# Generated by Django 3.2.8 on 2022-07-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), (2, 'Femenino')], default='Masculino', max_length=30, verbose_name='Género'),
        ),
    ]
