# Generated by Django 3.2.8 on 2022-07-24 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_employee_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 7, 24, 20, 52, 32, 645855, tzinfo=utc), verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_companyDate',
            field=models.DateField(blank=True, verbose_name='Fecha de ingreso'),
        ),
    ]
