# Generated by Django 3.2.8 on 2022-07-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20220724_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_companyDate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
    ]
