# Generated by Django 3.2.8 on 2022-07-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_employee_employee_companydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contact_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.contactemergency', verbose_name='Contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='employee',
            name='liability_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.liability', verbose_name='Carga'),
        ),
    ]
