# Generated by Django 3.2.8 on 2022-07-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20220726_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liability',
            name='liability_gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='', max_length=1, null=True, verbose_name='Género Carga'),
        ),
    ]
